### ISSUE TITLE
Text becomes blurry

### ISSUE THREAD

**Issue by Yo-Snowpro** [VixelCreates/GUIRevision#3]
When I turn the resource pack on, all the text becomes blurry and i cant see anything

**Comment by VixelCreates** [comment]
Hi! Sorry for the late reply.
There hasn't been a report of such a problem before, and I haven't personally experienced anything like this.
I'd be happy to help if you could provide details.

**Comment by Yo-Snowpro** [comment]
basically when i turn the resource pack on, in fabric 1.21. All the text becomes unreadable.

**Comment by VixelCreates** [comment]
could you check the log files related to your minecraft instance to see if there are any errors.
also you can check your mod/resourcepack list for any incompatibilities or send me a list of mods that you use
It would be great if you could send me a screenshot too

**Comment by VixelCreates** [comment]
> Same issue here, I have tried individually disabling each mod but I think the GUIRevisions make the text all squares. I also viewed the logs but I don't see any error
> 
> https://imgur.com/a/0Vtr5Y7

Thanks for the details.
I'm assuming this has something to do with the shader file inside the GUI revision, or another resourcepack modifying the same file.
But it's weird, I'm not experiencing this problem, so it's kinda hard to find the root of the problem.
I'm working on an overhaul update that will hopefully fix it.

**Comment by VixelCreates** [comment]
After doing some tests with other people who had this problem, it seems that the shader code is the cause. 
a hotfix is already available on modrinth
